### ISSUE TITLE
Error when trying to use GPU

### ISSUE THREAD

**Issue by vidarsumo** [business-science/modeltime.gluonts#15]
When creating new Python environment

```
py_install(
    packages = c(
        "mxnet-cu92",
        "gluonts==0.6.3",
        "numpy==1.16.6",
        "pandas==1.0.5",
        "scikit-learn==0.23.2",
        "matplotlib==3.3.2",
        "seaborn==0.11.0",
        "pathlib==1.0.1"
    ),
    envname = "gluonts_gpu_new",
    method = "conda",
    python_version = "3.6",
    pip     = TRUE
)
```
Everything works fine beside some warnings

![image](https://user-images.githubusercontent.com/69507559/104765802-63a2f400-5761-11eb-9d6a-9cb713d3ee9f.png)

Then I run into an error when I run this code
```
library(tidyverse)
env_path <- reticulate::conda_list() %>%
    filter(name == "gluonts_gpu_new") %>%
    pull(python)
Sys.setenv(GLUONTS_PYTHON = env_path)
library(modeltime.gluonts)
```
![image](https://user-images.githubusercontent.com/69507559/104765823-70274c80-5761-11eb-8c76-0c2619526dce.png)

**Comment by mdancho84** [comment]
Will look at this for 0.2.0 release. Trying for this weekend. We'll see.

**Comment by mdancho84** [comment]
I've added a vignette that covers using GPUs with modeltime.gluonts. https://business-science.github.io/modeltime.gluonts/articles/using-gpus.html

@vidarsumo Please verify this works for you. Thanks!

**Comment by flrs** [comment]
@mdancho84 @vidarsumo I have tested this and it works for me.

**Comment by mdancho84** [comment]
Adding in Florian's awesome CPU tutorial. https://gist.github.com/flrs/e80e7cd819cbaef74f0457abb687fbfa

**Comment by vidarsumo** [comment]
Sorry I simply forgott, but yes this works for me too.
