### ISSUE TITLE
Errors for setting dials for certain parameters (hyperparameter tuning)

### ISSUE THREAD

**Issue by flrs** [business-science/modeltime.gluonts#17]
I am trying to set up `modeltime.gluonts` for hyperparameter tuning. I am running the following code snippet:

```R
library(modeltime.gluonts)

model_spec_tune <- deep_ar(
  id = "id",
  freq = "5min",
  prediction_length = 10,
  num_layers = tune(),
  #num_cells = tune(), # same error here
  #scale = tune() # same error here
) %>%
  set_engine("gluonts_deepar")

parameters(model_spec_tune)
```

When executing the last line (`parameters(model_spec_tune)`), I get the following error:
```
Error (buggy.R#14): Problem with `mutate()` input `object`.
✖ Error when calling num_layers(): Error : 'num_layers' is not an exported object from 'namespace:modeltime.gluonts'

ℹ Input `object` is `purrr::map(call_info, eval_call_info)`.
```

A similar error pops up for the `num_cells` and `scale` parameters. Other parameters (e.g. `dropout`, `epochs`) work fine.

Am I missing something or is this a bug?

**Comment by tonyk7440** [comment]
I think the reason for this is that those parameters don't have tuning functions created yet, see https://github.com/business-science/modeltime.gluonts/issues/14

**Comment by mdancho84** [comment]
Yes, that is correct. I haven't yet created all of the potential tuning parameters.

**Comment by flrs** [comment]
Thanks @tonyk7440 and @mdancho84. Let's continue the discussion in #14.
