### ISSUE TITLE
New Model: DeepAR Torch

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime.gluonts#30]
Add support for Torch version of DeepAR, available in GluonTS 0.8.0. https://github.com/awslabs/gluon-ts/pull/1460/files

**Comment by mdancho84** [comment]
Initial Torch DeepAR is implemented in modeltime using: `deep_ar() %>% set_engine("torch")`

## Key References

- `deep_ar()` documentation: https://business-science.github.io/modeltime.gluonts/reference/deep_ar.html
- Torch DeepAR Pull Request: https://github.com/awslabs/gluon-ts/pull/1460
- Pytorch Lightning Trainer: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.html#pytorch_lightning.trainer.trainer.Trainer

## Example

``` r
library(modeltime.gluonts)
library(tidymodels)
library(tidyverse)
library(timetk)

splits <- walmart_sales_weekly %>%
    time_series_split(
        assess     = 26,
        cumulative = TRUE
    )
#> Using date_var: Date
#> Data is not ordered by the 'date_var'. Resamples will be arranged by `Date`.
#> Overlapping Timestamps Detected. Processing overlapping time series together using sliding windows.

model_fit_deepar_torch <- deep_ar(
    id                    = "id",
    freq                  = "W",
    prediction_length     = 26,
    lookback_length       = 52*2,
    epochs                = 10,
    scale                 = TRUE
) %>%
    set_engine("torch") %>%
    fit(Weekly_Sales ~ Date + id, training(splits))

modeltime_table(
    model_fit_deepar_torch
) %>%
    modeltime_calibrate(
        new_data = testing(splits),
        id       = "id"
    ) %>%
    modeltime_forecast(
        new_data      = testing(splits),
        actual_data   = walmart_sales_weekly,
        conf_interval = 0.95,
        conf_by_id    = TRUE
    ) %>%
    group_by(id) %>%
    plot_modeltime_forecast(
        .interactive = FALSE,
        .facet_ncol  = 2
    )
```

![](https://i.imgur.com/ZVJgq0o.png)

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Shafi2016** [comment]
Great!! Can we add external regressors to DeepAR model? Are you thinking to add [DeepVAR](https://ts.gluon.ai/api/gluonts/gluonts.model.deepvar.html) to Modeltime gluonts or with Torch.?

**Comment by mdancho84** [comment]
Not yet. We will investigate external regressors more soon.

**Comment by Shafi2016** [comment]
Thanks, @mdancho84
